### Simple objective: branin with sleeps to emulate delay

In [1]:
# silence TF warnings and info messages, only print errors
# https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
tf.get_logger().setLevel('ERROR')
import numpy as np
import math
import timeit

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
def objective(points):
    if points.shape[1] != 2:
        raise ValueError(f"Incorrect input shape, expected (*, 2), got {x.shape}")

    def branin(x):
        x0 = x[..., :1] * 15.0 - 5.0
        x1 = x[..., 1:] * 15.0

        b = 5.1 / (4 * math.pi ** 2)
        c = 5 / math.pi
        r = 6
        s = 10
        t = 1 / (8 * math.pi)
        scale = 1
        translate = 10

        return scale * ((x1 - b * x0 ** 2 + c * x0 - r) ** 2 + s * (1 - t) * np.cos(x0) + translate)
        
    observations = []
    for point in points:
        observation = branin(point)
        observations.append(observation)
    
    return observations

In [4]:
objective(np.array([[0.1, 0.5]]))

[array([32.96369168])]

### Here comes Trieste

In [5]:
from trieste.objectives.utils import mk_observer
from trieste.space import Box

search_space = Box([0, 0], [1, 1])

In [6]:
from trieste.data import Dataset

num_initial_points = 3
initial_query_points = search_space.sample(num_initial_points)
initial_observations = objective(initial_query_points.numpy())

In [7]:
initial_data = Dataset(query_points=initial_query_points, observations=tf.constant(initial_observations, dtype=tf.float64))

print(initial_data)

Dataset(query_points=<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.52496236, 0.72011192],
       [0.99852951, 0.70053815],
       [0.39182544, 0.17070116]])>, observations=<tf.Tensor: shape=(3, 1), dtype=float64, numpy=
array([[69.77988602],
       [58.48466555],
       [20.72779849]])>)


In [8]:
import gpflow
from trieste.models import create_model
from trieste.utils import map_values
import tensorflow_probability as tfp

from trieste.models.gpflow.config import GPflowModelConfig


def build_model(data):
    variance = tf.math.reduce_variance(data.observations)
    kernel = gpflow.kernels.RBF(variance=variance)
    gpr = gpflow.models.GPR(data.astuple(), kernel, noise_variance=1e-5)
    gpflow.set_trainable(gpr.likelihood, False)

    return GPflowModelConfig(**{
        "model": gpr,
        "optimizer": gpflow.optimizers.Scipy(),
        "optimizer_args": {
            "minimize_args": {"options": dict(maxiter=100)},
        },
    })

In [11]:
model_spec = build_model(initial_data)
model = create_model(model_spec)

model.optimize(initial_data)

In [12]:
from trieste.acquisition import LocalPenalizationAcquisitionFunction
from trieste.acquisition.rule import EfficientGlobalOptimization

local_penalization_acq = LocalPenalizationAcquisitionFunction(search_space, num_samples=2000)
local_penalization_acq_rule = EfficientGlobalOptimization(
    num_query_points=2, builder=local_penalization_acq)
points_chosen = local_penalization_acq_rule.acquire_single(search_space, initial_data, model)

In [13]:
points_chosen

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0., 0.],
       [1., 0.]])>

In [14]:
objective(points_chosen.numpy())

[array([308.12909601]), array([10.96088904])]

### Doing observations in separate processes

In [33]:
from multiprocessing import Process, Queue, Manager
import time
import sys
import psutil

num_workers = 3
num_observations = 10
dataset = initial_data

model_spec = build_model(initial_data)
model = create_model(model_spec)

model.optimize(initial_data)

local_penalization_acq = LocalPenalizationAcquisitionFunction(search_space)
local_penalization_acq_rule = EfficientGlobalOptimization(
    num_query_points=2, builder=local_penalization_acq)

m = Manager()
pq = m.Queue()
oq = m.Queue()

def observer_proc(points_queue, observations_queue, cpu_id):
    pid = os.getpid()
    
    current_process = psutil.Process()
    current_process.cpu_affinity([cpu_id])
    print(f"Process {pid}: set CPU to {cpu_id}", flush=True)
    
    while True:
        point_to_observe = points_queue.get()
        if (point_to_observe is None):
            return
        
        print(f"Process {pid}: observing data at point {point_to_observe}", flush=True)
        
        # insert some artificial delay
        # increases linearly with the absolute value of points
        # which means our evaluations will take different time, good for exploring async
        delay = 10 * np.sum(point_to_observe)
        print(f"Observer Process {pid} pretends like it's doing something for {delay:.2}s", flush=True)
        time.sleep(delay)
        new_observation = objective(point_to_observe)
        new_data = (point_to_observe, new_observation)
        
        print(f"Observer Process {pid}: observed data {new_data}", flush=True)
        
        observations_queue.put(new_data)


observer_processes = []

start = timeit.default_timer()
try:
    for i in range(psutil.cpu_count())[:num_workers]:
        observer_p = Process(target=observer_proc, args=(pq, oq, i))
        observer_p.daemon = True
        observer_p.start()

        observer_processes.append(observer_p)

    # init the queue with first batch of points
    points_chosen = local_penalization_acq_rule.acquire_single(search_space, initial_data, model)
    for point in points_chosen:
        pq.put(np.atleast_2d(point.numpy()))

    while len(dataset) < len(initial_data) + num_observations:
        pid = os.getpid()
        
        try:
            new_data = oq.get_nowait()
            print(f"Main Process {pid}: received data {new_data}", flush=True)
        except:
            continue

        new_data = Dataset(query_points=tf.constant(new_data[0], dtype=tf.float64),
                           observations=tf.constant(new_data[1], dtype=tf.float64),
                          )
        dataset = dataset + new_data

        model.update(dataset)
        model.optimize(dataset)

        new_points = local_penalization_acq_rule.acquire_single(search_space, dataset, model).numpy()
        print(f"Main Process {pid}: acquired point {new_points}", flush=True)
        for point in new_points:
            pq.put(np.atleast_2d(point))
finally:
    for prc in observer_processes:
        prc.terminate()
        prc.join()
        prc.close()
stop = timeit.default_timer()

print(f"Time : {stop - start}")

Process 20852: set CPU to 0
Process 20857: set CPU to 1
Process 20865: set CPU to 2
Process 20852: observing data at point [[0. 0.]]Process 20857: observing data at point [[1. 0.]]

Observer Process 20852 pretends like it's doing something for 0.0sObserver Process 20857 pretends like it's doing something for 1e+01s

Observer Process 20852: observed data (array([[0., 0.]]), [array([308.12909601])])
Main Process 7228: received data (array([[0., 0.]]), [array([308.12909601])])
Main Process 7228: acquired point [[0.81649026 0.69271001]
 [0.011063   0.00624165]]
Process 20852: observing data at point [[0.011063   0.00624165]]Process 20865: observing data at point [[0.81649026 0.69271001]]

Observer Process 20852 pretends like it's doing something for 0.17sObserver Process 20865 pretends like it's doing something for 1.5e+01s

Observer Process 20852: observed data (array([[0.011063  , 0.00624165]]), [array([287.35014426])])
Main Process 7228: received data (array([[0.011063  , 0.00624165]]),

In [32]:
dataset

Dataset(query_points=<tf.Tensor: shape=(7, 2), dtype=float64, numpy=
array([[0.52496236, 0.72011192],
       [0.99852951, 0.70053815],
       [0.39182544, 0.17070116],
       [0.        , 0.        ],
       [0.42677059, 0.19428767],
       [1.        , 0.        ],
       [1.        , 0.        ]])>, observations=<tf.Tensor: shape=(7, 1), dtype=float64, numpy=
array([[ 69.77988602],
       [ 58.48466555],
       [ 20.72779849],
       [308.12909601],
       [ 12.84672966],
       [ 10.96088904],
       [ 10.96088904]])>)